on: 
  push:
  schedule:
    - cron: "30 13 * * 6"
  workflow_dispatch:

jobs:
  ctb:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
            python-version: '3.8'
            architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: ctb.py
        run: |
          python ctb.py
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
            file-path: |
              _CTB_Stop.json
              _CTB_rt.json
              _CTB_Stop_Route.json
            github-token: ${{ secrets.GITHUB_TOKEN }}
            commit-msg: Fetched Data | Update per week
            branch: data
